### ISSUE TITLE
Off-by-one error in front-end time range code

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pdp#110]
The front-end code uses OPeNDAPs DDS response to determine the length of the time dimension for each dataset.

Unfortunately, there appears to be an off-by-one error. The DDS response returns the *length* of the time dimension, and then the front-end code [naively uses](https://github.com/pacificclimate/pdp/blob/master/pdp/static/js/pdp_raster_map.js#L88) the length as the final raster index.

However, in the OPeNDAP spec [array indices are inclusive](https://docs.opendap.org/index.php/DAP4:_Specification_Volume_1#Array_Subsetting_in_Index_Space) at both the start and stop of the range. So the ending index should be `length - 1`, I believe.

Not sure how we didn't run into this before... maybe the client would just close the connection when it received all of the data?

**Comment by rod-glover** [comment]
Copied from an email from @jameshiebert : 

After having looked at it a big longer, I'm not certain that it's as
simple as I believed in my initial assessment (in the issue
report). It uses a bunch of information (which may or may not agree
with each other).

Things that have to be considered:

* OPeNDAP DDS response: gives the definitive length of the time dimension
* OPeNDAP DAS response: gives the calendar and units of the time dimension
* What date is selected in the UI, and does it need to change (e.g. if
  the calendar changed or whether it's now out of range).
* Many a couple others that I'm forgetting.

Note that this information isn't actually sufficient to match a
calendar date to a time index. To do that, you actually need to
download the time variable (which we don't do). So at present, we're
faking it. If the time units is days, we just blindly assume that t=5
will be start date + 5 days. This will surely come to bite us at
sometime, and that time might be now (since, the time values are [int]
+ .5 for this data set). So that's a possible line of inquiry as to
where the off-by-one is coming from.

If you can find a quick/short fix, please use that. But don't be
afraid to rewrite for clarity and robustness if you can do it in a
short amount of time. This is the last patch for milestone 2.7.0, so
I'd like to get it out in pretty short order.

**Comment by jameshiebert** [comment]
An example:

Open the [Downscaled GCMs page](https://data.pacificclimate.org/portal/downscaled_gcms/map/). The default dataset will be `tasmax_day_BCCAQv2+ANUSPLIN300_CanESM2_historical+rcp26_r1i1p1_19500101-21001231`.

Note that the length of the time variable is 55115 for that dataset:

```bash
$ curl 'https://data.pacificclimate.org/data/downscaled_gcms/tasmax_day_BCCAQv2+ANUSPLIN300_CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc.dds?time'
Dataset {
    Float64 time[time = 55115];
} tasmax_day_BCCAQv2%2BANUSPLIN300_CanESM2_historical%2Brcp26_r1i1p1_19500101-21001231%2Enc;
```

So, a time variable of length 55115 should correspond to indices 0 to 55114 (since OPeNDAP uses an inclusive end range), but if you right click or hover on the "Download" link, you'll see that it goes to an ending index of 55115.

Switch to another CanRCM dataset or a GFDL dataset (both of which have 365 day calendars) and you'll see the same thing. Switch to HadGEM2, and you'll see similar behaviour with an ending index of 54360 (360 day calendar). Etc.
