### ISSUE TITLE
help request

### ISSUE THREAD

**Issue by patjlittle** [pacificclimate/pdp#19]
Hello PCIC data portal,

I am a hydrologist working on a project whereby I am assembling datasets that will be used to run hydrologic models for the BC River Forecast Centre. I am currently figuring out how to download downscaled GCM daily data (Tmin, Tmax, and Precip) for 159 specific locations that correspond to climate station locations in BC (ie. stations in the EC, ENV-ASP and FW networks). I have a few questions about this data and how to go about doing this.

1. Will the historical (i.e. 1950-2014) data differ between the different climate models and scenarios?

2. Is there a way to download data by inputting a specific lat-long coordinate rather than polygon selection? Looking at your advanced/programmatic usage help page it looks like it will be possible however your example using a station id is for PCDS data. Can a similar script be written for downloading Statistically Downscaled GCM Scenario data for a specific lat-long or station id?

3. I am an intermediate level R user and am an absolute beginner to using NetCDF data. I am attempting to learn how to use NetCDF for this project - do you have any useful scripts (for R) or manuals/tutorials that may be useful for importing PCIC NetCDF data into R and extracting data for a particular lat-long (from a NetCDF file) into an R data frame?

Thank you very much for any help you can provide.

My email is plittle@watersmith.ca and phone is 250-460-1812

Thanks

Patrick Little, MSc, AAg

**Comment by jameshiebert** [comment]
I'll try and answer each of your three questions in turn.

Your first question is outside of the scope of using our data portal, and is more of a question about how to use information from climate models. I *can* tell you that yes, the data will definitely differ and you will likely want to consult with the hydrologists and climatologists at [PCIC](http://www.pacificclimate.org/).

**Comment by patjlittle** [comment]
Thanks James

I actually just emailed Arelia Werner, who is a friend of mine, about that issue. I realized it might be more up her alley.

Cheers
Patrick

**Comment by jameshiebert** [comment]
2) There is no built-in way to enter specific coordinates and download data for that coordinate. The application is designed for downloading bulk, spatiotemporal data. As such, it's somewhat easier to download *lots* of data than it is to download minimal subsets. E.g. it's actually really slow to download a timeseries at a single point. If your sites are clustered together, you're better off downloading a hyperslab subset that covers a number of sites and then extracting the timeseries locally.

Getting back to relating the geographic coordinates to the raster coordinates, you can [download the structure of the dataset](http://tools.pacificclimate.org/dataportal/downscaled_gcms/catalog/pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc.dds) with the dds OPeNDAP resposne, and then [download the values of the lat/lon dimensions](http://tools.pacificclimate.org/dataportal/downscaled_gcms/data/pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc.ascii?lat,lon) and try and relate them yourself. It's not super easy, but the information is there to do it.

**Comment by jameshiebert** [comment]
3) Our NetCDF output *should* follow the [Climate Forecast (CF) Convensions](http://cfconventions.org/). So there shouldn't be anything in particular about *PCIC's* NetCDF files, that are necessarily any different than any others. It should be self describing enough, if you are familiar with NetCDF.

If you are not, as an R User, I'd recommend the [reference manual](http://cran.r-project.org/web/packages/ncdf4/ncdf4.pdf) for the [ncdf4 package](http://cran.r-project.org/web/packages/ncdf4/index.html). If you were into Python, I like [h5py](http://www.h5py.org/) much better (which we utilize heavily in the data portal code itself).

We don't yet have any great "How to use NetCDF" tutorials that are specific to our downscaled climate model output, but if we ever write one, I'll be sure to let you know.

Best of luck and let me know if you have any further questions.

**Comment by patjlittle** [comment]
Thanks very much James,

I will get into this next week and may have some further questions for you. I think I have figured out how to extract data from a netCDF file for a single lat long using R.   

I will take your recommendation and download large swaths of the province at once. Do you have any advice on how large I should go per download? My points are scattered across the province so I will need to cover almost the whole province in the end but am wondering how large an area is too large to download at once.

Thanks
Patrick

**Comment by basilveerman** [comment]
Hi Patrick,

The data portal can accommodate requests as large as the original data source. I would recommend downloading the entire area of interest. Our server can deliver data at around 10MB/s per request, meaning the entire province would be transmitted in ~15 minutes per model (assuming the "Statistically Downscaled GCM Scenarios" portal, right?). If the network speed is lacking resulting in request taking a long time and being prone to transfer errors, only then would I recommend selecting smaller subsections.

Cheers,
Basil

**Comment by AreliaTW** [comment]
I see that you want to use the statistically downscaled climate data to drive a hydro model and (compare that to?) the VIC SWE gridded hydrologic data. There are a few key differences between the downscaled climate scenarios and hydrologic model output that make them challenging to compare: 

Statistically downscaled climate scenarios (climate) http://www.pacificclimate.org/data/statistically-downscaled-climate-scenarios
1) Based on Coupled Model Inter-Comparison Project: CMIP5 (more recent)
2) Gridded historical climate observations used for calibration: ANUSPLIN
3) Downscaling methods: BCSD and BCCAQ
4) Downscaling calibrated: 1979-2000

Gridded hydrologic model output (hydro)
http://www.pacificclimate.org/data/gridded-hydrologic-model-output
1) Based on Coupled Model Inter-Comparison Project: CMIP3
2) Gridded historical climate observations used for calibration: VIC FORCINGS
3) Downscaling method: BCSD
4) Downscaling calibrated: 1950-2006

We have the BCSD downscaling results that were used to drive the VIC Hydrologic Model. However, they are not currently on the Data Portal. We will be working on this in the near future. Given the current availability of data it would be challenging to compare the SWE from the VIC Hydrologic Model (run with BCSD downscaled CMIP3 GCMs all run 1) to results of running your hydrologic model with the climate data (run with BCSD/BCCAQ downscaled CMIP5 GCMs run depends on model). Although initial testing has shown that the RCP8.5 results are similar to the A2 results. If you took CGCM3 RCP8.5 (climate) and compared them to CMCM3 A2 (hydro) the results should be within the same ball park. This might help your GCM selection. You could select GCMs that overlap between the hydro projections (HadCM, GFDL2.1, CSIRO35, CCSM3, HadGEM1,MIROC3.2,CGCM3,ECHAM5) and climate projections (CNRM-CM5-r1,CanESM2-r1,ACCESS-0-r1,inmcm4-r1,CSIRO-Mk3-6-0-r1,CCSM4-r2,MIROC5-r3,MPI-ESM-LR-r3,HadGEM2-CC-r1,MRI-CGCM3-r1,GFDL-ESM2G-r1,HadGEM2-ES-r1), namely GFDL2.1, CSIRO35, CCSM3, HadGEM1,MIROC3.2 and CGCM3. The GCM were selected with different approaches in each project. The GCM selection and downscaling procedure for the hydro simulations is described here:
http://www.pacificclimate.org/sites/default/files/publications/Werner.HydroModelling.FinalReport1.Apr2011.pdf

The GCM selection and downscaling procedure (BCCAQ) reports are still internal for the statistically downscaled climate scenarios portal. The general overview is that the GCMS have been ranked according to spread from one model to the next. If you only had the resources to run 6 of the 12 selected GCMs it would be best to pick the top six (CNRM-CM5-r1,CanESM2-r1,ACCESS-0-r1,inmcm4-r1,CSIRO-Mk3-6-0-r1,CCSM4-r2) to ensure you explore the widest range of uncertainty. The BCCAQ method uses daily GCM data whereas the BCSD method uses monthly GCM data. We are in the midst of publishing papers that outline some of the strengths of BCCAQ over BCSD. Our analysis shows that the BCCAQ method can be used to more accurately downscale some climate extremes and project hydrologic extremes an area where BCSD can have challenges because it resamples daily events from the historical record and scales them. BCSD estimates the change in magnitude of temperature and precipitation events almost on par with BCCAQ, but doesn't always get the right sequence of events. We are still exploring the implications of this in climate and hydrologic modelling. 

To answer your question about the differences in the historical records; under different representative concentration pathways RCP 2.6, RCP 4.5 or RCP 8.5 (CMIP5) downscaled climate results will be the same for a given GCM from 1950 to 2005 for BCSD and BCCAQ and under different emissions scenarios B1, A2 or A1B (CMIP3) hydrologic model results monthly values will be basically the same for the same GCM from 1950 to 2000. In the case of the hydro results, there will be some variation for daily since the daily values are resampled randomly.
