### ISSUE TITLE
Why so many decimal points on the PRISM and BCCAQ data?

### ISSUE THREAD

**Issue by dspittlehouse** [pacificclimate/pdp#20]
PRISM and the BCAQ temperature and precipitation data come with numerous decimal points. The uncertainty in the data is greater than 0.1C or 1 mm. Thus the reporting increment (indication of data accuracy) should only be at best one decimal. This would save you storage space and me download time. Any application that claims to need more decimals on these data is got a problem. I can accept a justification for not rounding the data during its creation by PRISM and the statistical magic/divination of the BCCAQ process. But once done the temperature and precipitation data should be rounded off otherwise supplying with all these decimals implies some level of accuracy you do not have.

Dave S.

**Comment by basilveerman** [comment]
Hi Dave,

Thank you for your comments. I'll forward the reccomendation along to the data creators to find out the justification for serving the raw output rather than preprocessing the data with this in mind.

Regarding how this affects file size: The data is stored as 32 bit floats. While storing the data as a 16 bit short would be possible, it would require altering the data using a scale factor and offset. Anyone downloading the data would then need to process the data back to the original values and we decided against this. Even if the data was delivered rounded, we would still keep the data as 32 bit floats and the download time would remain unchanged.

-Basil
