### ISSUE TITLE
Incorrect download links generated for vic_gen1 portal

### ISSUE THREAD

**Issue by basilveerman** [pacificclimate/pdp#31]
VIC input data was added to the vic_gen1 portal and this has a different extent than the output data. When switching layers between the original data [bf, aet, swe, R, sm] and the new data [tmin, tmax, precip, wind] with a previously selected polygon, the lat/lon indices of the generated download link do not change to reflect the new layer's changed extent.

**Comment by jameshiebert** [comment]
Technically, this bug affects all raster portals for which different layers have different grids/extents. At present this is on the VIC page, but depending on what data is added, it could be any other page in the future.

Since the fix is only one line of code per page (an event registration), and is relatively inexpensive (2 extra AJAX requests on layer changes), I think it would be wise to implement the fix for all raster pages.
