### ISSUE TITLE
MoTIe data has strange wind units

### ISSUE THREAD

**Issue by doylejg** [pacificclimate/pdp#35]
Hopefully this is the correct place to post this question, but I have noticed some funny units for wind in the data. For example,
from:
```bash
$ ncdump MoTIe/64093.nc -h
	ACTUAL_WIND_SPEED:units = "None" ;
	MEASURED_WIND_SPEED1:units = "km h-1" ;
```
By inspection of the wind fields I would guess that they are actually in *knots* or perhaps *m s-1*. The numbers just seem to be too low for *km hr-1*. 

Thank you for your time.

**Comment by basilveerman** [comment]
Hi doylejg,

I took a look at a sample of the data we parse directly from MoTI and it is in km/h.

```xml
<wind index="1" type="average-scalar-speed-over-60minutes">
  <value units="km/h">2.422</value>
</wind>
```

We mirror exactly what MoTI provides us and do not perform any quality control. There is a chance that their data is incorrect, but you would need to contact them directly about that. Do the values being an average rather than max change your expectations?

**Comment by doylejg** [comment]
Hi basilveerman,

Okay I'll follow up with them eventually when I start working directly with the winds. But the *ACTUAL_WIND_SPEED* should be *km/hr*

**Comment by basilveerman** [comment]
Hmm... That data came in with a previous data dump (we have used real-time sources since April 2011 which do not have ACTUAL_WIND_SPEED) and the metadata was not inserted correctly. I would expect that yes, the data is in km/h, but I'll have to double check and get back to you to be sure.

**Comment by faronium** [comment]
Seems that it has changed through time, so maybe all of the above? I'll ask the network manager if he knows if there were systematic changes across the network or if this was limited to this station. Furthermore, I'll ask what the units are for each period. 

![motie_64093_actual_wind_speed](https://cloud.githubusercontent.com/assets/11469553/11158979/c766738c-8a10-11e5-8da5-a05384a2a3d7.png)

**Comment by doylejg** [comment]
Yes I thought something like that might have been the case. Well thanks again for looking into it. Have a great weekend!

**Comment by jameshiebert** [comment]
That plot is one of those "a picture is worth a thousand words" pictures.

**Comment by faronium** [comment]
none of the words we like to see unfortunately. I'll be in touch when I hear from the network manager.

**Comment by faronium** [comment]
The ACTUAL_WIND_SPEED is most likely the instantaneous or most recent short term average speed for the given observation time. Possibly included in the measurement suite to align with the manually observed data from other stations or even to diagnose issues with the station. Because of those issues, you are probably better off with the MEASURED_WIND_SPEED1. Don't worry, I'm not letting myself off the hook, just trying to help you project along. Cheers.

**Comment by doylejg** [comment]
Thanks but don't rush on my behalf, I am using the precip data currently and just stored the wind for future use.

**Comment by jameshiebert** [comment]
I think that we've all come to the agreement that this is not a *software* issue with the `pdp` package, so I'm closing this ticket. If more discussion is needed to resolve the data issues, feel free to take the discussion offline.

**Comment by doylejg** [comment]
Okay thank you for your input, i guess I'll contact the people directly.

**Comment by faronium** [comment]
You can keep communicating with me. Search for Faron Anslow on PCIC's web pages to get my contact info (I'm unsure if spammers can scrape git pages so don't want to put it here).
