### ISSUE TITLE
Raster portals don't support multiple grid resolutions on the same page

### ISSUE THREAD

**Issue by mschnorb** [pacificclimate/pdp#37]
When attempting to download precipitation data from Gridded Hydrologic Model Output data portal, the resultant netCDF file only serves data over a truncated spatial domain of 47.5N to 57.7N by -139W to -125.5W (see image below), when data for all of BC are expected.

![precip_hydro-portal](https://cloud.githubusercontent.com/assets/9890345/12403401/72d638e6-bde8-11e5-8d8b-6bb6c4513dde.png)

Steps taken:
1. Select HadCM A1B
2. Select Precipitation variable
3. Set date range from 1950/01/01 to 1979/12/31
4. Output format NetCDF (default)
5. Click download

Expected precipitation data for the selected date range covering all of BC (as shown in the portal map preview). However, the resultant netCDF file only provides precipitation over on a truncated spatial array (lat=164, lon=216) as opposed to all of BC.Note that the same problem was encountered when attempting to download precipitation for the GFDL A1B scenario.

Time: 18/01/2016 1:32 pm (PST)
IP address: 142.104.194.119

**Comment by jameshiebert** [comment]
Thanks for the detailed bug report. This *is* actually a known issue, but apparently no one has written it up on the issue tracker, so thanks for doing so.

The root of the problem is that we have several variables on this page with different spatial domains / grid properties. And when we designed the page, we unfortunately assumed that all of the listed datasets on a given page would have the same spatial properties. We didn't check this assumption when adding the forcings data to this page, so essentially, you will see this issue with any of the forcings data sets (precip, tasmin, tasmax).

If you really just want to download the whole domain, there's an easy temporary work around (until we fix the problem).

1. Select everything that you want (dataset, time range, output format) *except* for the spatial domain
1. Copy/paste the download link (e.g. http://tools.pacificclimate.org/dataportal/data/hydro_model_out/pr+tasmin+tasmax+wind_day_CSIRO35_A2_run1_19500101-21001231.nc.nc?pr[0:54787][0:163][0:215]&)
1. Omit the grid parameters at the end of the link. E.g. replace ``[0:163][0:215]`` with ``[:][:]``
1. Use the edited link to download the full spatial domain

**Comment by mschnorb** [comment]
Thanks James. ~MS
