### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by stephenban** [pacificclimate/pdp#78]
I’m currently looking at using some data from the BC Station Data portal, and I noticed that most stations (nearly all FLNRO-WMB) only have timeseries data running up until October-ish 2000. Was there a change in protocol past this point, or did data cease getting collected altogether at these stations?

**Comment by jameshiebert** [comment]
This dataset is highly heterogeneous, so its hard to generalize without talking about specific stations.

Do you want to shoot us an e-mail if you want to go into more details on this question? The GH issues on this repository are supposed to be for *software* issues.

**Comment by stephenban** [comment]
Hi James,

Sorry, the FAQ was a little unclear on where one is supposed to submit questions regarding the data itself.

I was doing a search for stations with daily average relative humidity data from Jan 1st, 1990-December 31st 2017, and it seems that nearly all of the FLNRO-WMB stations stopped collecting data (at least for this particular parameter) on October 1, 2000, if not before.

I do get a lot more stations that extend past the year 2000 if I don’t constrain the collection frequency to daily, but I was curious about the FLNRO-WMB stations and what happened to those stations after October 2000.

But basically in the end all I’m looking for is a climatology of daily humidity values across the province for stations located in or near provincial parks, and hoping there might be a way to extract those data without having to manually select all the stations one by one.

Thanks,
Stephen

**Comment by jameshiebert** [comment]
>  if I don’t constrain the collection frequency to daily

Ah, you're probably missing out on all of the stations that transitioned from daily measurements to *hourly* measurements (due to automation).

If you're just looking for climatologies, I would just tick the "Only include stations with 1971-2000 climatology" box and select the "Relative Humidity (Mean)" variable. This turns up 579 stations, across the province.

> but I was curious about the FLNRO-WMB stations and what happened to those stations after October 2000

My database query actually turns up very few stations (less than 10 IIRC) that actually *end* in October 2000. I bet that you're excluding data that they started collecting automatically after that time.
